
# This is a basic workflow to help you get started with Actions
name: AZURE push image and deploy app service
on:
#   push:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - uses: azure/docker-login@v1
        with:
          login-server: gitcontaineryprod.azurecr.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - run: |
          docker build . -t gitcontaineryprod.azurecr.io/gitcontaineryprod:${{ github.sha }}
          docker push gitcontaineryprod.azurecr.io/gitcontaineryprod:${{ github.sha }}
          
      - uses: azure/webapps-deploy@v2
      - with:
          app-name: 'gitdev0321'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          images: 'iamopstesting.azurecr.io/test:${{ github.sha }}'

