# This is a basic workflow to help you get started with Actions
name: AZURE push image and deploy app service
on:
#   push:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - uses: azure/docker-login@v1
        with:
          login-server: gitcontaineryprod.azurecr.io
          username: 'gitcontaineryprod'
          password: 's7mAHZ+HfzASwYKGKbh9n86M7IX5TcAW'

      - run: |
          docker build . -t gitcontaineryprod.azurecr.io/gitcontaineryprod:${{ github.sha }}
          docker push gitcontaineryprod.azurecr.io/gitcontaineryprod:${{ github.sha }}
          
      - uses: azure/webapps-deploy@v2
      - with:
          app-name: 'gitdev0321'
          slot-name: '12'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          images: 'gitcontaineryprod.azurecr.io/test:${{ github.sha }}'
      
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          
      - name: Azure CLI script
        uses: azure/CLI@v1
        with:
          azcliversion: 2.34.1
          inlineScript: |
            az webapp deployment slot swap -g testingiamops_group -n test123iamops --slot 12 \
                  --target-slot production
